// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZeVkhOOwLFAZDqtdKeEXvggRot9jox8I',
    appId: '1:610746973484:android:42e28051dde58856fa8089',
    databaseURL: 'https://fir-use-case-default-rtdb.europe-west1.firebasedatabase.app/',
    messagingSenderId: '610746973484',
    projectId: 'fir-use-case',
    storageBucket: 'fir-use-case.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSXqCjtcj_EE_UxlKbuYA-DGa1aLB7CaE',
    appId: '1:610746973484:ios:de381105c060158ffa8089',
    messagingSenderId: '610746973484',
    projectId: 'fir-use-case',
    databaseURL: 'https://fir-use-case-default-rtdb.europe-west1.firebasedatabase.app/',
    storageBucket: 'fir-use-case.firebasestorage.app',
    iosBundleId: 'com.example.advanceFlutter',
  );
}
